/++
Physical assembly of a planned ID3v2.4 frame sequence.

This module is the first layer that executes all existing-frame actions
of `Id3v24TagWritePlan` together:

- `preserveOriginal` copies the unchanged native frame representation;
- `regenerate` executes the planned ordinary text-frame regeneration;
- `discard` emits no bytes;
- `rejectWrite` blocks serialization.

After all surviving existing frames have been emitted in original native
order, newly introduced ordinary text-information frames are appended in
`Id3v24TagWritePlan.newFrames` order.

The current assembler deliberately supports only source tags without
tag-level unsynchronisation.

Why:

- preserved frames retain their original physical frame-data bytes;
- regenerated and new frames currently emit ordinary non-tag-unsynchronised
  bytes;
- mixing those representations under one future tag-level
  unsynchronisation flag would be ambiguous until whole-tag
  unsynchronisation writing exists.

Frame-level unsynchronisation remains safe: preserved frames retain their
native frame flag and bytes, while regenerated frames use the explicit
regeneration policy.

No ID3 tag header, extended header, padding or container bytes are
serialized here.
+/
module audiotag.id3v2.v24.frame_sequence_write;

import audiotag.core.result :
    ParseResult;

import audiotag.core.serialization :
    SerializationError,
    SerializationErrorCode,
    SerializationResult;

import audiotag.metadata.edit :
    MetadataTreeEdit;

import audiotag.id3v2.v24.canonical_projection :
    Id3v24CanonicalProjection;

import audiotag.id3v2.v24.frame_preserve_write :
    serializePreservedId3v24Frame;

import audiotag.id3v2.v24.frame_write_plan :
    Id3v24FrameWriteAction;

import audiotag.id3v2.v24.planned_new_text_write :
    serializeId3v24PlannedNewTextFrame;

import audiotag.id3v2.v24.planned_text_write :
    serializeId3v24PlannedTextRegeneration;

import audiotag.id3v2.v24.tag_write_plan :
    Id3v24TagWritePlan;


/++
Result of assembling one complete currently supported frame sequence.

The outer parse result retains source-structure errors that can arise
while executing an existing-frame regeneration.

The inner serialization result retains writer/planner/output errors.
+/
alias Id3v24FrameSequenceSerializationResult =
    ParseResult!(
        SerializationResult!(ubyte[])
    );


/++
Wraps one writer failure without misclassifying it as malformed source
input.
+/
private Id3v24FrameSequenceSerializationResult
writerFailure(
    SerializationError error
)
    @safe
{
    return
        Id3v24FrameSequenceSerializationResult
            .success(
                SerializationResult!(ubyte[])
                    .failure(error)
            );
}


/++
Appends one serialized frame to a locally assembled byte sequence.
+/
private void appendFrameBytes(
    ref ubyte[] output,
    const(ubyte)[] frame
)
    @safe
{
    output ~= frame;
}


/++
Assembles all currently supported frame output for one semantic tag plan.

Existing frames retain original native order. A regenerated frame
occupies the same sequence position as its source frame. Discarded
frames occupy no output position.

New fields have no source-native placement information in the current
edit model. They are therefore appended after all surviving existing
frames, preserving `plan.newFrames` order.

Params:
    projection = Original native-plus-canonical projection.
    edit = Canonical edit overlay used to create `plan`.
    plan = Complete semantic tag write plan.
    sourceTagUnsynchronised = Whether the source tag used global ID3v2.4
        unsynchronisation. Currently only `false` is supported.

Returns:
    Complete concatenated native frame bytes, an outer source parse
    failure, or an inner serialization failure.
+/
Id3v24FrameSequenceSerializationResult
serializeId3v24PlannedFrameSequence(
    const(Id3v24CanonicalProjection) projection,
    const(MetadataTreeEdit) edit,
    const(Id3v24TagWritePlan) plan,
    bool sourceTagUnsynchronised = false
)
    @safe
{
    /*
     * Whole-tag unsynchronisation writing has not yet been defined.
     * Reject before producing any mixture of source-physical and newly
     * generated byte representations.
     */
    if (sourceTagUnsynchronised)
    {
        return
            writerFailure(
                SerializationError(
                    SerializationErrorCode
                        .unsupportedRepresentation
                )
            );
    }

    if (!plan.writable)
    {
        return
            writerFailure(
                SerializationError(
                    SerializationErrorCode
                        .unsupportedRepresentation
                )
            );
    }

    if (
        plan.existingFrames.length !=
        projection.frames.length
    )
    {
        return
            writerFailure(
                SerializationError(
                    SerializationErrorCode
                        .inconsistentStructure,
                    plan.existingFrames.length,
                    plan.existingFrames.length,
                    projection.frames.length
                )
            );
    }

    if (
        plan.newFrames.length !=
        edit.newFields.length
    )
    {
        return
            writerFailure(
                SerializationError(
                    SerializationErrorCode
                        .inconsistentStructure,
                    plan.newFrames.length,
                    plan.newFrames.length,
                    edit.newFields.length
                )
            );
    }

    ubyte[] output;

    /*
     * Existing-frame entries are produced by the sequence planner in
     * source-native order. Verify that relationship instead of relying
     * on it silently.
     */
    foreach (
        sequenceIndex,
        const entry;
        plan.existingFrames.entries
    )
    {
        if (
            entry.sourceFrameIndex !=
            sequenceIndex
        )
        {
            return
                writerFailure(
                    SerializationError(
                        SerializationErrorCode
                            .inconsistentStructure,
                        sequenceIndex,
                        entry.sourceFrameIndex,
                        projection.frames.length
                    )
                );
        }

        if (
            entry.sourceFrameIndex >=
            projection.frames.length
        )
        {
            return
                writerFailure(
                    SerializationError(
                        SerializationErrorCode
                            .inconsistentStructure,
                        entry.sourceFrameIndex,
                        entry.sourceFrameIndex,
                        projection.frames.length
                    )
                );
        }

        final switch (entry.plan.action)
        {
            case Id3v24FrameWriteAction.preserveOriginal:
            {
                auto serialized =
                    serializePreservedId3v24Frame(
                        projection.frames[
                            entry.sourceFrameIndex
                        ].native.envelope
                    );

                if (serialized.hasError)
                {
                    return
                        writerFailure(
                            serialized.error
                        );
                }

                appendFrameBytes(
                    output,
                    serialized.value
                );

                break;
            }

            case Id3v24FrameWriteAction.regenerate:
            {
                size_t regenerationIndex;
                size_t matchCount;

                foreach (
                    candidateIndex,
                    const regeneration;
                    plan.regenerations
                )
                {
                    if (
                        regeneration.sourceFrameIndex ==
                        entry.sourceFrameIndex
                    )
                    {
                        regenerationIndex =
                            candidateIndex;

                        ++matchCount;
                    }
                }

                if (matchCount != 1)
                {
                    return
                        writerFailure(
                            SerializationError(
                                SerializationErrorCode
                                    .inconsistentStructure,
                                entry.sourceFrameIndex,
                                matchCount,
                                1
                            )
                        );
                }

                auto executed =
                    serializeId3v24PlannedTextRegeneration(
                        projection,
                        edit,
                        plan,
                        regenerationIndex,
                        false
                    );

                if (executed.hasError)
                {
                    return
                        Id3v24FrameSequenceSerializationResult
                            .failure(
                                executed.error
                            );
                }

                auto serialized =
                    executed.value;

                if (serialized.hasError)
                {
                    return
                        writerFailure(
                            serialized.error
                        );
                }

                appendFrameBytes(
                    output,
                    serialized.value
                );

                break;
            }

            case Id3v24FrameWriteAction.discard:
                /*
                 * Explicit semantic decision: the source frame contributes
                 * no bytes to the resulting sequence.
                 */
                break;

            case Id3v24FrameWriteAction.rejectWrite:
                /*
                 * `plan.writable` should already have prevented this.
                 * Treat a contradictory supplied plan as a writer-plan
                 * failure rather than an assertion so public execution
                 * remains defensive.
                 */
                return
                    writerFailure(
                        SerializationError(
                            SerializationErrorCode
                                .inconsistentStructure,
                            entry.sourceFrameIndex
                        )
                    );
        }
    }

    /*
     * The current edit model retains new canonical fields separately and
     * does not assign an insertion point among source-native frames.
     *
     * Deterministic initial placement policy:
     * append all new frames after surviving existing frames in plan order.
     */
    foreach (
        newFramePlanIndex;
        0 .. plan.newFrames.length
    )
    {
        auto serialized =
            serializeId3v24PlannedNewTextFrame(
                edit,
                plan,
                newFramePlanIndex
            );

        if (serialized.hasError)
        {
            return
                writerFailure(
                    serialized.error
                );
        }

        appendFrameBytes(
            output,
            serialized.value
        );
    }

    return
        Id3v24FrameSequenceSerializationResult
            .success(
                SerializationResult!(ubyte[])
                    .success(output)
            );
}


version (unittest)
{
    import audiotag.core.cursor :
        ByteCursor;

    import audiotag.core.span :
        ByteSpan;

    import audiotag.metadata.field :
        MetadataField,
        MetadataKey;

    import audiotag.metadata.value :
        MetadataText,
        MetadataTextList,
        MetadataUrl,
        MetadataValue;

    import audiotag.id3v2.v24.canonical_mapping :
        Id3v24CanonicalMappingResult;

    import audiotag.id3v2.v24.frame :
        Id3v24FrameEnvelope,
        parseId3v24FrameEnvelope;

    import audiotag.id3v2.v24.native_frame :
        Id3v24NativeFrame;

    import audiotag.id3v2.v24.tag_write_plan :
        planId3v24CanonicalTagWrite;

    import audiotag.id3v2.v24.text_information :
        decodeId3v24TextInformationFrame;

    import audiotag.id3v2.v24.writer_policy :
        Id3v24WriteContext;


    private MetadataField textField(
        string key,
        string value
    )
        @safe
    {
        MetadataValue wrapped =
            MetadataText(value);

        return
            MetadataField(
                MetadataKey(key),
                wrapped
            );
    }


    private MetadataField textListField(
        string key,
        string[] values
    )
        @safe
    {
        MetadataValue wrapped =
            MetadataTextList(values);

        return
            MetadataField(
                MetadataKey(key),
                wrapped
            );
    }


    private MetadataField urlField(
        string key,
        string value
    )
        @safe
    {
        MetadataValue wrapped =
            MetadataUrl(value);

        return
            MetadataField(
                MetadataKey(key),
                wrapped
            );
    }


    private Id3v24FrameEnvelope parseSourceFrame(
        const(ubyte)[] bytes,
        size_t sourceOffset = 0
    )
        @safe
    {
        auto cursor =
            ByteCursor(
                ByteSpan(
                    bytes,
                    sourceOffset
                )
            );

        auto parsed =
            cursor.parseId3v24FrameEnvelope();

        assert(parsed.hasValue);
        assert(cursor.empty);

        return parsed.value;
    }


    private Id3v24NativeFrame nativeFromBytes(
        const(ubyte)[] bytes,
        size_t sourceOffset = 0
    )
        @safe
    {
        auto native =
            Id3v24NativeFrame.init;

        native.envelope =
            parseSourceFrame(
                bytes,
                sourceOffset
            );

        return native;
    }
}


/// Preserve, regenerate, discard and new-frame output form one sequence.
unittest
{
    const ubyte[] originalTitle =
        [
            'T', 'I', 'T', '2',
            0x00, 0x00, 0x00, 0x09,
            0x00, 0x00,

            0x03,
            'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l'
        ];

    const ubyte[] unknownFrame =
        [
            'X', '0', '0', '1',
            0x00, 0x00, 0x00, 0x02,
            0x00, 0x00,

            0xAA, 0xBB
        ];

    const ubyte[] originalAlbum =
        [
            'T', 'A', 'L', 'B',
            0x00, 0x00, 0x00, 0x04,
            0x00, 0x00,

            0x03,
            'O', 'l', 'd'
        ];

    auto projection =
        Id3v24CanonicalProjection.init;

    /*
     * Native order:
     *
     * 0 TIT2 -> regenerated
     * 1 X001 -> preserved
     * 2 TALB -> discarded
     */
    projection.append(
        nativeFromBytes(
            originalTitle,
            100
        ),
        Id3v24CanonicalMappingResult.success(
            textField(
                "title",
                "Original"
            )
        )
    );

    projection.append(
        nativeFromBytes(
            unknownFrame,
            200
        ),
        Id3v24CanonicalMappingResult
            .unsupported()
    );

    projection.append(
        nativeFromBytes(
            originalAlbum,
            300
        ),
        Id3v24CanonicalMappingResult.success(
            textField(
                "album",
                "Old"
            )
        )
    );

    /*
     * Canonical source indices are title=0, album=1.
     * The unknown native frame contributed no canonical field.
     */
    auto edit =
        MetadataTreeEdit.forSource(
            projection.metadata
        );

    edit.replaceSourceField(
        0,
        textField(
            "title",
            "New"
        )
    );

    edit.removeSourceField(1);

    edit.appendNewField(
        textListField(
            "artist",
            ["A", "B"]
        )
    );

    const plan =
        planId3v24CanonicalTagWrite(
            projection,
            edit,
            Id3v24WriteContext.tagOnly()
        );

    assert(plan.writable);

    assert(
        plan.existingFrames.regenerateCount ==
        1
    );

    assert(
        plan.existingFrames.preserveCount ==
        1
    );

    assert(
        plan.existingFrames.discardCount ==
        1
    );

    assert(plan.newFrameCount == 1);

    auto assembled =
        serializeId3v24PlannedFrameSequence(
            projection,
            edit,
            plan
        );

    assert(assembled.hasValue);

    auto serialized =
        assembled.value;

    assert(serialized.hasValue);

    auto cursor =
        ByteCursor(
            ByteSpan(
                serialized.value[],
                1000
            )
        );

    /*
     * Existing frame 0 remains first, but with regenerated semantics.
     */
    auto first =
        cursor.parseId3v24FrameEnvelope();

    assert(first.hasValue);

    assert(
        first.value.header.id[] ==
        "TIT2"
    );

    auto firstDecoded =
        first.value
            .decodeId3v24TextInformationFrame();

    assert(firstDecoded.hasValue);

    assert(
        firstDecoded.value.text.values ==
        ["New"]
    );

    /*
     * Existing frame 1 remains second and byte-preserved.
     */
    const preservedStart =
        cursor.position;

    auto second =
        cursor.parseId3v24FrameEnvelope();

    assert(second.hasValue);

    assert(
        second.value.header.id[] ==
        "X001"
    );

    assert(
        second.value.data.data ==
        [0xAA, 0xBB]
    );

    assert(
        serialized.value[
            preservedStart ..
            preservedStart + unknownFrame.length
        ] ==
        unknownFrame
    );

    /*
     * TALB was discarded. The new TPE1 therefore follows immediately
     * after all surviving existing frames.
     */
    auto third =
        cursor.parseId3v24FrameEnvelope();

    assert(third.hasValue);

    assert(
        third.value.header.id[] ==
        "TPE1"
    );

    auto thirdDecoded =
        third.value
            .decodeId3v24TextInformationFrame();

    assert(thirdDecoded.hasValue);

    assert(
        thirdDecoded.value.text.values ==
        ["A", "B"]
    );

    assert(cursor.empty);
}


/// Multiple new fields retain edit insertion order at sequence tail.
unittest
{
    const projection =
        Id3v24CanonicalProjection.init;

    auto edit =
        MetadataTreeEdit.forSource(
            projection.metadata
        );

    edit.appendNewField(
        textField(
            "title",
            "Title"
        )
    );

    edit.appendNewField(
        textField(
            "album",
            "Album"
        )
    );

    edit.appendNewField(
        textListField(
            "artist",
            ["Artist"]
        )
    );

    const plan =
        planId3v24CanonicalTagWrite(
            projection,
            edit,
            Id3v24WriteContext.tagOnly()
        );

    assert(plan.writable);

    auto assembled =
        serializeId3v24PlannedFrameSequence(
            projection,
            edit,
            plan
        );

    assert(assembled.hasValue);

    auto serialized =
        assembled.value;

    assert(serialized.hasValue);

    auto cursor =
        ByteCursor(
            ByteSpan(
                serialized.value[]
            )
        );

    auto first =
        cursor.parseId3v24FrameEnvelope();

    auto second =
        cursor.parseId3v24FrameEnvelope();

    auto third =
        cursor.parseId3v24FrameEnvelope();

    assert(first.hasValue);
    assert(second.hasValue);
    assert(third.hasValue);

    assert(first.value.header.id[] == "TIT2");
    assert(second.value.header.id[] == "TALB");
    assert(third.value.header.id[] == "TPE1");

    assert(cursor.empty);
}


/// A blocked semantic plan cannot produce a partial frame sequence.
unittest
{
    const ubyte[] bytes =
        [
            'T', 'I', 'T', '2',
            0x00, 0x00, 0x00, 0x02,
            0x10, 0x00,

            0x03, 'X'
        ];

    auto projection =
        Id3v24CanonicalProjection.init;

    projection.append(
        nativeFromBytes(bytes),
        Id3v24CanonicalMappingResult.success(
            textField(
                "title",
                "X"
            )
        )
    );

    auto edit =
        MetadataTreeEdit.forSource(
            projection.metadata
        );

    edit.replaceSourceField(
        0,
        textField(
            "title",
            "Y"
        )
    );

    const plan =
        planId3v24CanonicalTagWrite(
            projection,
            edit,
            Id3v24WriteContext.tagOnly()
        );

    assert(!plan.writable);

    auto assembled =
        serializeId3v24PlannedFrameSequence(
            projection,
            edit,
            plan
        );

    assert(assembled.hasValue);

    auto serialized =
        assembled.value;

    assert(serialized.hasError);

    assert(
        serialized.error.code ==
        SerializationErrorCode
            .unsupportedRepresentation
    );
}


/// Semantically valid non-text new frames await their physical codec.
unittest
{
    const projection =
        Id3v24CanonicalProjection.init;

    auto edit =
        MetadataTreeEdit.forSource(
            projection.metadata
        );

    edit.appendNewField(
        urlField(
            "commercialUrl",
            "https://example.test/"
        )
    );

    const plan =
        planId3v24CanonicalTagWrite(
            projection,
            edit,
            Id3v24WriteContext.tagOnly()
        );

    assert(plan.writable);

    auto assembled =
        serializeId3v24PlannedFrameSequence(
            projection,
            edit,
            plan
        );

    assert(assembled.hasValue);

    auto serialized =
        assembled.value;

    assert(serialized.hasError);

    assert(
        serialized.error.code ==
        SerializationErrorCode
            .unsupportedRepresentation
    );
}


/// Global source-tag unsynchronisation is blocked until tag writing exists.
unittest
{
    const ubyte[] bytes =
        [
            'X', '0', '0', '1',
            0x00, 0x00, 0x00, 0x02,
            0x00, 0x00,

            0xAA, 0xBB
        ];

    auto projection =
        Id3v24CanonicalProjection.init;

    projection.append(
        nativeFromBytes(bytes),
        Id3v24CanonicalMappingResult
            .unsupported()
    );

    auto edit =
        MetadataTreeEdit.forSource(
            projection.metadata
        );

    const plan =
        planId3v24CanonicalTagWrite(
            projection,
            edit,
            Id3v24WriteContext.unchanged()
        );

    assert(plan.writable);

    auto assembled =
        serializeId3v24PlannedFrameSequence(
            projection,
            edit,
            plan,
            true
        );

    assert(assembled.hasValue);

    auto serialized =
        assembled.value;

    assert(serialized.hasError);

    assert(
        serialized.error.code ==
        SerializationErrorCode
            .unsupportedRepresentation
    );
}
